#ifndef BOARD_IDS_H__
#define BOARD_IDS_H__

/* ID values must match the values define by pinLayouts in refernce/speeduino.ini. */

typedef enum board_ids_t
{
  BOARD_ID_INVALID_0 = 0,
  BOARD_ID_SPEEDUINO_V0_2 = 1,
  BOARD_ID_SPEEDUINO_V0_3 = 2,
  BOARD_ID_SPEEDUINO_V0_4 = 3,
  BOARD_ID_01_05_MX5_PNP = 6,
  BOARD_ID_96_97_MX5_PNP = 8,
  BOARD_ID_NA6_MX5_PNP = 9,
  BOARD_ID_TURTANA_PCB = 10,
  BOARD_ID_PLAZOMAT_IO_REV_0_1 = 20,
  BOARD_ID_DAZ_V6 = 30,
  BOARD_ID_BMW_PNP = 31,
  BOARD_ID_NO2C = 40,
  BOARD_ID_UA4C = 41,
  BOARD_ID_BLITZ_BOX_BL49_SP = 42,
  BOARD_ID_DIY_EFI_CORE4_V1_0 = 45,
  BOARD_ID_DVJCODE_TEENSY_REV_A = 50,
  BOARD_ID_DVJCODE_TEENSY_REV_B = 51,
  BOARD_ID_JUICE_BOX = 53,
  BOARD_ID_DROPBEAR = 55,
  BOARD_ID_BEAR_CUB_TEENSY_4_1 = 56,
  BOARD_ID_Black_STM32F407VET6_V0_1 = 60,
  BOARD_ID_RUSEFI_FRANKENSO_STM32_F407_DISC = 70,
} board_ids_t;

#endif /* BOARD_IDS_H__ */

